# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b3c92c9f0e2de9a14549e8db2a95ca88bb7ebe84a289b88762065ecd99f82b426f4c25d1c692d310b54db84ac4dce3c7cee1664626b9936310a79be24fbaa6f

test:
  secret_key_base: 14dad06c7e43935e3603a54028f46e175cdebc815378719b60e074b9e3fa4a7a17a93aa47d112fadb21d474703488cea6d7e2e3044d0e0758e19de9d41f1e01d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
